import {money} from './engine.js';
import {historyTabs} from './record-view.js';

const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=value=>new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(value));
const signed=value=>`${BigInt(value)>0n?'＋':''}${money(value)}`;
const tone=value=>BigInt(value)>0n?'positive':BigInt(value)<0n?'negative':'';
export const meterLabel=id=>`TRIP ${id.toUpperCase()}`;
const metric=(label,value,key)=>`<div><dt>${label}</dt><dd data-trip-stat="${key}">${value}</dd></div>`;
const count=value=>`${value.toLocaleString('ja-JP')}回`;
function meter(trip,{busy,drafts}){
  const s=trip.stats,label=meterLabel(trip.id),name=drafts[trip.id]??trip.name;
  return `<section class="surface stats-surface trip-meter" data-trip="${trip.id}" aria-labelledby="trip-title-${trip.id}"><div class="trip-heading"><h2 id="trip-title-${trip.id}">${label}</h2><span class="trip-state">${trip.startedAt?'計測中':'未開始'}</span></div>${trip.name!==label?`<p class="trip-name">${escape(trip.name)}</p>`:''}${trip.startedAt?`<p class="trip-start">計測開始 <time datetime="${escape(trip.startedAt)}" data-trip-start>${date(trip.startedAt)}</time></p><div class="stats-hero trip-hero"><span>累計損益</span><strong class="${tone(s.pnlTotal)}" data-trip-stat="pnlTotal">${signed(s.pnlTotal)}</strong><dl class="stats-capital">${metric('投入元本相当',money(s.initialTotal),'initialTotal')}${metric('最終資産合計',money(s.finalTotal),'finalTotal')}</dl></div><dl class="stats-overview">${metric('対象ゲーム数',`${s.plays}ゲーム`,'plays')}${metric('優勝',count(s.wins),'wins')}${metric('負債退場',count(s.debtExits),'debtExits')}</dl><details class="stats-detail trip-records"><summary>この期間の記録</summary><dl class="stats-metrics">${metric('資金枯渇・ロスカット',count(s.fundsDepleted),'fundsDepleted')}${metric('最高最終資産',s.highestFinal===null?'—':money(s.highestFinal),'highestFinal')}${metric('最高到達資産',s.highestPeak===null?'—':money(s.highestPeak),'highestPeak')}${metric('最大負債',s.plays?money(s.maxDebt):'—','maxDebt')}${metric('最大取引額',s.plays?money(s.maxPosition):'—','maxPosition')}</dl>${trip.startGameId?`<a class="stats-link record-open-link" href="#match/${escape(trip.startGameId)}?from=trips">最初の対象ゲームを見る →</a>`:'<p class="stats-definition">この期間に終了したCPU対戦はまだありません。</p>'}</details>`:'<p class="stats-empty">好きなタイミングで計測を開始。<br>その後に終了したゲームの戦績がたまります。</p>'}<button type="button" class="${trip.startedAt?'secondary':'primary'} full trip-reset" data-action="trip-reset" data-meter="${trip.id}" ${busy?'disabled':''}>${trip.startedAt?`${label}をリセット`:'計測を開始'}</button><details class="trip-settings" ${drafts[trip.id]!==undefined?'open':''}><summary>名前を変更</summary><form data-trip-form="${trip.id}"><label for="trip-name-${trip.id}">計測の名前<input id="trip-name-${trip.id}" data-trip-name="${trip.id}" value="${escape(name)}" maxlength="20" required autocomplete="off" ${busy?'disabled':''}></label><button type="submit" class="secondary" ${busy?'disabled':''}>名前を保存</button></form></details></section>`;
}
export function tripsView({state,data,error='',hasGame=false,pendingCount=0,busy=false,mutationError='',retryable=false,notice='',drafts={}}){
  const head=`<div class="stats-top"><h1>TRIPメーター</h1><a href="#" class="text-button stats-link">${hasGame?'ゲームに戻る':'スタート画面へ'}</a></div>${historyTabs('trips')}`;
  if(state!=='ready')return `<section class="surface stats-surface">${head}${state==='loading'?'<p class="stats-message" role="status">TRIPを読み込み中…</p>':`<p class="stats-message" role="alert">${escape(error||'TRIPを読み込めませんでした。')}</p><button class="secondary" data-action="reload-trips">再読み込み</button>`}</section>`;
  return `<div class="stats-layout"><section class="surface stats-surface trip-intro">${head}<p class="stats-scope">開始後に終了した、あなたのCPU対戦を計測。<br>A／Bは、それぞれ別の時点から数えられます。</p><details class="record-about"><summary>計測とリセットについて</summary><p class="stats-definition">リセットすると、その時点から数え直します。過去のゲームと生涯戦績は残ります。開始前に終了した試合は、後から保存しても含めません。開始時刻より後に終了した試合が対象です。対面は本人未指定のため、TRIPには含めません。</p></details>${pendingCount?`<p class="stats-pending" role="status">保存完了を確認できていない試合が${pendingCount}件あります。<button class="text-button" data-action="retry-records" ${busy?'disabled':''}>保存を再試行</button></p>`:''}${busy?'<p class="trip-notice" role="status">TRIPの設定を保存中…</p>':notice?`<p class="trip-notice" role="status">${escape(notice)}</p>`:''}${mutationError?`<div class="trip-error" role="alert"><p>${escape(mutationError)}</p><div>${retryable?'<button class="secondary" data-action="retry-trip">保存を再試行</button>':''}<button class="text-button" data-action="reload-trips">再読み込み</button></div></div>`:''}</section><div class="trip-grid">${data.trips.map(trip=>meter(trip,{busy,drafts})).join('')}</div></div>`;
}
